### ISSUE TITLE
WhoRahh!!!

### ISSUE THREAD

**Issue by rfair404** [DecaturMakers/RFID-System#1]
Thanks for putting it online. out of curiosity, could I put this on my own arduino?

**Comment by lewlefton** [comment]
It's open source so I don't see why not.  You'll need a matching RFID reader though.

**Comment by tcontis** [comment]
Yes, as Lew pointed out you will need a keypad. With the recent changes we need, you would also need an ESP8266. We currently are using a Wemos D1, a board that is like an Arduino with an embedded ESP8266.
