### ISSUE TITLE
A REST API interface please.

### ISSUE THREAD

**Issue by rfair404** [DecaturMakers/RFID-System#2]
how to make an http request to find out if an id (string) is associated with an active account?

**Comment by lewlefton** [comment]
I think the architecture we have discussed goes the other way.  When an RFID token needs to be deactivated, we will notify a Raspberry Pi that will update the Arduino(s) DB.  That way access isn't dependent on network being up.

**Comment by tcontis** [comment]
Perfectly stated, Lew.
